---
title: "Adding row number from Dada2"
output: html_notebook
---

The Dada2 algorithm returns the output of the sequences, can it return another element with some info about the header

```{r}
# library(dada2)
library(tidyverse)
library (here)
```

Load the files

```{r}
F1s <- list.files(path = here("data", "fastqs"),
                  pattern = 
                    "*R1_001.fastq")

R1s <- list.files(path = here("data", "fastqs"),
                  pattern = 
                    "*R2_001.fastq")

output <- here("output", paste0("output_", Sys.Date()))

dir.create(file.path(output, "filtered"), recursive = T)

tibble (file1 = here("data", "fastqs", F1s), file2 =here("data", "fastqs", R1s), basename = F1s) %>% 
  separate(basename, into = "basename", sep= "_L001_R1", remove = F) %>% 
  mutate(filtF1 = file.path(output, "filtered", paste0(basename, "_F1_filt.fastq.gz")),
         filtR1 = file.path(output, "filtered", paste0(basename, "_R1_filt.fastq.gz"))) %>% 
   mutate (outFs = pmap(.l= list (file1, filtF1, file2, filtR1),
                       .f = function(a, b, c, d) {
                         filterAndTrim(a,b,c,d,
                                      # truncLen=c(params$trimming.length.Read1,params$trimming.length.Read2),
                                      truncLen=c(200,150),
                                       maxN=0, maxEE=c(2,2), truncQ=2, #rm.phix=TRUE,
                                       compress=TRUE, multithread=TRUE )
                       } )) -> until.filter
  
until.filter %>% 
pull(outFs) %>% set_names(F1s) %>% 
  flatten_df(.id = "sample") -> just.filter.outs
  
just.filter.outs %>% 
  filter(str_detect(sample, "S19"))

```

Now derep

```{r}
until.filter %>% 
  mutate(derepF1 = map(filtF1, derepFastq)) %>% 
  mutate(derepR1 = map(filtR1, derepFastq)) %>% 
  mutate(tracking = pmap(.l = list(outFs, derepF1, derepR1),
                         .f = function(a,b,c){
                           flatten_df(a) %>% 
                             mutate(derepF = b$map,
                                    derepR = c$map) -> df
                           return(df)
                         })) -> until.derep 

until.derep %>% 
pull(tracking) %>% 
  map(~ggplot(.x,aes(x = derepF, y = derepR)) + geom_hex())

until.derep %>% 
  pull(tracking) %>% 
  map(~.x %>% distinct(derepF))
```


```{r}
until.derep %>% 
pull(tracking) %>% 
  map(~.x %>% tally_wide(rows = derepF, cols = derepR))

```

Let's get the error estimates

```{r}
until.derep %>% 
  mutate( errF1 = map(filtF1, ~ learnErrors(.x, multithread=TRUE,verbose = 0)),     # Calculate errors
          errR1 = map(filtR1, ~ learnErrors(.x, multithread=TRUE,verbose = 0))) -> until.errors
```

Now, I think dada2 also keeps the info in the same format as derep

```{r}
until.errors %>% 
  mutate(dadaF1  = map2(derepF1,errF1, ~ dada(.x, err = .y, multithread = TRUE)),  # dada2
          dadaR1  = map2(derepR1,errR1, ~ dada(.x, err = .y, multithread = TRUE))) -> until.dada
```

Explore the dada2
```{r}
until.dada %>% 
  pull(dadaF1) -> dadaf1

dadaf1 %>% 
  map(~.x$map %>% as_tibble ) %>% flatten_df() %>% distinct(value)

```

So it seems like a left_join will do

```{r}
until.dada %>% 
  mutate(tracking.dada = pmap(.l = list(tracking, dadaF1, dadaR1),
                         .f = function(a,b,c){
                           a %>% 
                             left_join(tibble(dadaF = b$map) %>% rownames_to_column("derepF") %>% mutate(derepF = as.numeric(derepF))) %>% 
                             left_join(tibble(dadaR = c$map) %>% rownames_to_column("derepR") %>% mutate(derepR = as.numeric(derepR)))
                           
                         } )) %>% 
  pull(tracking.dada)
```

